# Generated by Django 5.0.1 on 2024-01-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_bookid_alter_bookdetails_detailsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='BookID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookdetails', to='Books.book'),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='NumberOfPages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Publisher',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
